intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import impl_libs += libhello%lib{hello}

lib{Vulkan-Headers}: {hxx}{**} hxx{*.hpp} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_base/include"

# Export options.
#
lib{Vulkan-Headers}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root" "-I$src_base/include"
  cxx.export.libs = $intf_libs
}

# Install into the vulkan/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx}{*}:
{
  install         = include/vulkan/
  install.subdirs = true
}
