intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{Vulkan-Headers}: h{**} $intf_libs

# Build options.
#
c.poptions =+ "-I$src_base/include"

# Export options.
#
lib{Vulkan-Headers}:
{
  c.export.poptions = "-I$src_base/include"
  c.export.libs = $intf_libs
}

# Install into the Vulkan-Headers/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
include/
{
  h{*}:
  {
    install         = include/
    install.subdirs = true
  }
}
