intf_libs = # Interface dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{Vulkan-Headers}: h{** -version} h{version} $intf_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
h{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
c.poptions =+ "-I$out_root" "-I$src_root"

# Export options.
#
lib{Vulkan-Headers}:
{
  c.export.poptions = "-I$out_root" "-I$src_root"
  c.export.libs = $intf_libs
}

# Install into the Vulkan-Headers/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
h{*}:
{
  install         = include/Vulkan-Headers/
  install.subdirs = true
}
